### PR TITLE
Clarified ECHOAPI_HOST parameter in the README.md file

### PR DESCRIPTION
**Pull request by leathersole**
The default `ECHOAPI_HOST` value is not valid, it should be described at all times.

### CODE REVIEW

**Comment by mikz** [comment]
I think it would be good to remove the bogus value from the template and just leave it required field.

**Comment by leathersole** [comment]
@mikz Thanks for reviewing. I removed the default value.

**Comment by maneta** [comment]
Actually no need to do that

**Comment by maneta** [comment]
@leathersole could you squash the commits (so we could commit again) so we could test the circle ci build?

Thanks!

**Pull request merged**
