### PR TITLE
Adding CORS support

### LINKED ISSUE #19: CORS Support Echo Api
As pointed by @unleashed there is no CORS support on the echo-api. All deployments using the default documentation on a openshift cluster are failing right now. 

One option would be activating this gem:

* https://github.com/britg/sinatra-cross_origin

### PR DESCRIPTION
**Pull request by maneta**
This adds CORS support to all routes on the echo api. It should close #19.

### CODE REVIEW

**Comment by maneta** [comment]
@unleashed now everything should be fine :) Thanks for the heads up! 👍

**Comment by maneta** [comment]
@mikz yes it is broken, I was doing my tests with localhost and curl and clearly was not doing it right. I will review it...

**Comment by maneta** [comment]
Hey guys I have to put this on hold for a couple of days because we need some stuff urgent at the ops team.

**Comment by maneta** [comment]
@mikz @unleashed Now CORS is working but I´m not sure it is too "naive". please give me your thoughts about it. Thanks!

**Comment by unleashed** [comment]
A proper implementation needs to serve `OPTIONS` preflight requests. You can check tje backend implementation for that and for extra control headers.

**Comment by maneta** [comment]
@unleashed Will do for the `OPTIONS` preflight. Im not sure if we want to add some extra control headers just for the sake of being actually a thin e"echo api" without creating too much boiler plate.

**Comment by unleashed** [comment]
@maneta the extra headers are those required by preflight, but also those telling the browser which content is accessible from JS, like exposing specific headers. Not sure whether headers will be exposed by default or not, so

**Comment by maneta** [comment]
@unleashed Now I got it clear, I´m on it. Tks!

**Comment by mikz** [comment]
Just use the gem no? No need to implement own stuff.

**Comment by maneta** [comment]
@mikz following the documentation, the gem was not working and also @unleashed said that he was not too happy with the gem implementation and probably in his view would be better to implement our stuff. The two options are perfectly fine for me.

**Comment by mikz** [comment]
There is https://github.com/cyu/rack-cors which should be just few lines of configuration to allow everything.

**Comment by maneta** [comment]
@mikz yes with the gem rack/cors CORS is working.

**Comment by mikz** [comment]
Confirmed working!

**Pull request merged**
